spring.application.name=Invitacion

server.port=${PORT:8080}

logging.pattern.dateformat=yyyy-MM-dd'T'HH:mm:ss.SSSXXX

spring.main.banner-mode=off

spring.thymeleaf.cache=${THYMELEAF_CACHE:false}

spring.datasource.url=jdbc:mysql://${MYSQLHOST:localhost}:${MYSQLPORT:3306}/${MYSQLDATABASE:invitacion}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

spring.datasource.username=${MYSQLUSER:admin}
spring.datasource.password=${MYSQLPASSWORD:123456}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.properties.hibernate.format_sql=${SQL_FORMAT:false}
logging.level.org.hibernate.SQL=${SQL_LOG:WARN}
logging.level.org.type.descriptor.sql.BasicBinder=${SQL_BINDER_LOG:WARN}